Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Models/ErrorViewModel.cs
namespace ACME.Frontend.Web.Mvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Controllers/ProductController.cs
using ACME.Backend.Models;
using ACME.Frontend.Web.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ACME.Frontend.Web.Mvc.Controllers;

public class ProductController : Controller
{
    private readonly ILogger<ProductController> _logger;
    private readonly IHttpClientFactory _httpFactory;

    public ProductController(ILogger<ProductController> logger, IHttpClientFactory httpFactory)
    {
        _logger = logger;
        _httpFactory = httpFactory;
    }

    public async Task<IActionResult> ProductgroupsAsync()
    {
        var http = _httpFactory.CreateClient("data");
        var model = await http.GetFromJsonAsync<ProductGroupModel[]>("productGroup?page=1&count=20");
        return View(model);
    }
    public async Task<IActionResult> AllProductsAsync(int page = 1, int count = 20)
    {
        var http = _httpFactory.CreateClient("data");
        var model = await http.GetFromJsonAsync<ProductModel[]>($"product?page={page}&count={count}");
        ViewBag.Page = page;
        ViewBag.HasNext = model?.Count() == count;
        return View(model);
    }
    public async Task<IActionResult> ProductsAsync(long pgid, int page = 1, int count = 20)
    {
        var http = _httpFactory.CreateClient("data");
        var model = await http.GetFromJsonAsync<ProductModel[]>($"productgroup/{pgid}/products?page={page}&count={count}");
        ViewBag.GroupId = pgid;
        ViewBag.Page = page;
        ViewBag.HasNext = model?.Count() == count;
        return View(model);
    }
    public async Task<IActionResult> ProductDetailAsync(long pid)
    {
        var http = _httpFactory.CreateClient("data");
        var model = await http.GetFromJsonAsync<ProductModel>($"product/{pid}");
        return View(model);
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/ViewComponents/PricesViewComponent.cs
using ACME.Backend.Models;
using Microsoft.AspNetCore.Mvc;

namespace ACME.Frontend.Web.Mvc.ViewComponents;

public class PricesViewComponent: ViewComponent
{
    private readonly IHttpClientFactory _httpClientFactory;

    public PricesViewComponent(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    public async Task<IViewComponentResult> InvokeAsync(long pid)
    {
        var client = _httpClientFactory.CreateClient("data");
        var data = await client.GetFromJsonAsync<PriceModel[]>($"product/{pid}/prices?page=1&count=200");
        return View(data);
    }
}

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/ViewComponents/ReviewViewComponent.cs
using ACME.Backend.Models;
using Microsoft.AspNetCore.Mvc;

namespace ACME.Frontend.Web.Mvc.ViewComponents;

public class ReviewViewComponent: ViewComponent
{
    private readonly IHttpClientFactory _httpClientFactory;

    public ReviewViewComponent(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    public async Task<IViewComponentResult> InvokeAsync(long pid)
    {
        var client = _httpClientFactory.CreateClient("data");
        var tasks = new Task<ReviewModel[]>[3];
        tasks[0]= client.GetFromJsonAsync<ReviewModel[]>($"product/{pid}/expertreviews?page=1&count=200")!;
        tasks[1] = client.GetFromJsonAsync<ReviewModel[]>($"product/{pid}/consumerreviews?page=1&count=200")!;
        tasks[2] = client.GetFromJsonAsync<ReviewModel[]>($"product/{pid}/webreviews?page=1&count=200")!;
        await Task.WhenAll( tasks );
        var data = tasks.SelectMany(t => t.Result).ToArray();
        return View(data);
    }
}

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/ViewComponents/SpecificationViewComponent.cs
using ACME.Backend.Models;
using Microsoft.AspNetCore.Mvc;

namespace ACME.Frontend.Web.Mvc.ViewComponents;

public class SpecificationViewComponent: ViewComponent
{
    private readonly IHttpClientFactory _httpClientFactory;

    public SpecificationViewComponent(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    public async Task<IViewComponentResult> InvokeAsync(long pid)
    {
        var client = _httpClientFactory.CreateClient("data");
        var data = await client.GetFromJsonAsync<SpecificationModel[]>($"product/{pid}/specifications?page=1&count=200");
        return View(data);
    }
}

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Views/Product/AllProducts.cshtml
@model ACME.Backend.Models.ProductModel[]
@{
    ViewData["Title"] = $"Products";
}

<div class="list-group">
    @foreach (var product in Model)
    {
        <a class="list-group-item list-group-item-action" asp-action="ProductDetail" asp-route-pid="@product.Id">
            <img class="rounded float-start" src="https://angular-training.azureedge.net/@product.Image" alt="Card image cap">
            <div class="card-body">
                <p class="card-text">@product.BrandName @product.Name</p>
            </div>
        </a>
    }
</div>
<nav>
    <ul class="pagination align-items-center">
        @if (ViewBag.Page > 1) {
            <li class="page-item">
                <a class="page-link" asp-action="AllProducts"  asp-route-page="@(ViewBag.Page-1)">Previous</a>
                </li>
            <li class="page-item">
                <a class="page-link" asp-action="AllProducts"  asp-route-page="@(ViewBag.Page-1)">@(ViewBag.Page - 1)</a>
                </li>
        }
        <li class="page-item">
            <a class="page-link" asp-action="AllProducts"  asp-route-page="@ViewBag.Page">@ViewBag.Page</a>
         </li>
        @if(ViewBag.HasNext) {
            <li class="page-item">
                <a class="page-link" asp-action="AllProducts" asp-route-page="@(ViewBag.Page+1)">@(ViewBag.Page + 1)</a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-action="AllProducts" asp-route-page="@(ViewBag.Page+1)">Next</a>
            </li>
        }       
    </ul>
</nav>

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Views/Product/ProductDetail.cshtml
@model ACME.Backend.Models.ProductModel
@{
    ViewData["Title"] = $"{Model.BrandName} {Model.Name}";
}
<div class="text-left">
    <div class="row">
        <h1>@Model.BrandName @Model.Name</h1>
    </div>
    <div class="row">
            <img class="rounded float-start" style="width:400px" src="https://angular-training.azureedge.net/@Model.Image" alt="@Model.Name">
    </div>    
</div>

<ul class="nav nav-tabs">
    <li class="nav-item">
        <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#specs" type="button" role="tab" aria-controls="specs" aria-selected="true">Specifications</button>
    </li>
    <li class="nav-item">
        <button class="nav-link" data-bs-toggle="tab" data-bs-target="#prices" type="button" role="tab" aria-controls="prices" aria-selected="false">Prices</button>
    </li>
    <li class="nav-item">
        <button class="nav-link" data-bs-toggle="tab" data-bs-target="#reviews" type="button" role="tab" aria-controls="reviews" aria-selected="false">Reviews</button>
    </li>
</ul>
<div class="tab-content">
    <div id="specs" class="tab-pane fade show active">
        <vc:specification pid="@Model.Id"></vc:specification>        
    </div>
    <div id="prices" class="tab-pane fade">
        <vc:prices pid="@Model.Id"></vc:prices>
    </div>
    <div id="reviews" class="tab-pane fade">
        <vc:Review pid="@Model.Id"></vc:Review>
    </div>
</div>

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Views/Product/Productgroups.cshtml
@model ACME.Backend.Models.ProductGroupModel[]
@{
    ViewData["Title"] = "Home Page";
}


<div class="row">
    @foreach (var group in Model)
    {
        <div class="col-md-4">
            <a class="btn btn-light" asp-action="Products" asp-route-pgid="@group.Id" asp-route-page=1>
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="https://angular-training.azureedge.net/@group.Image" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">@group.Name</p>
                    </div>
                </div>
            </a>
        </div>
    }
</div>

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Views/Product/Products.cshtml
@model ACME.Backend.Models.ProductModel[]
@{
    ViewData["Title"] = $"Products";
}

<div class="list-group">
    @foreach (var product in Model)
    {
        <a class="list-group-item list-group-item-action" asp-action="ProductDetail" asp-route-pid="@product.Id">
            <img class="rounded float-start" src="https://angular-training.azureedge.net/@product.Image" alt="Card image cap">
            <div class="card-body">
                <p class="card-text">@product.BrandName @product.Name</p>
            </div>
        </a>
    }
</div>
<nav>
    <ul class="pagination align-items-center">
        @if (ViewBag.Page > 1) {
            <li class="page-item">
                <a class="page-link" asp-action="Products" asp-route-pgid="@ViewBag.GroupId" asp-route-page="@(ViewBag.Page-1)">Previous</a>
                </li>
            <li class="page-item">
                <a class="page-link" asp-action="Products" asp-route-pgid="@ViewBag.GroupId" asp-route-page="@(ViewBag.Page-1)">@(ViewBag.Page - 1)</a>
                </li>
        }
        <li class="page-item">
            <a class="page-link" asp-action="Products" asp-route-pgid="@ViewBag.GroupId" asp-route-page="@ViewBag.Page">@ViewBag.Page</a>
         </li>
        @if(ViewBag.HasNext) {
            <li class="page-item">
                <a class="page-link" asp-action="Products" asp-route-pgid="@ViewBag.GroupId" asp-route-page="@(ViewBag.Page+1)">@(ViewBag.Page + 1)</a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-action="Products" asp-route-pgid="@ViewBag.GroupId" asp-route-page="@(ViewBag.Page+1)">Next</a>
            </li>
        }       
    </ul>
</nav>

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Views/Shared/Components/Prices/Default.cshtml
@using System.Globalization;
@model ACME.Backend.Models.PriceModel[]

@{
    var nl = new CultureInfo("nl-NL");
}
<div class="list-group">
    @foreach (var price in Model)
    {
        <div class="list-group-item list-group-item-action">
            <div class="col-form-label-lg">@price.ShopName</div>
            <div class="col-md-10" data-type="currency">@price.BasePrice.ToString("C", nl)</div>
        </div>
    }
</div>

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Views/Shared/Components/Review/Default.cshtml
@model ACME.Backend.Models.ReviewModel[]


@foreach (var review in Model)
{
    <div class="mt-5 d-flex justify-content-between align-items-left">
        <div class="small-ratings">
            @for (var idx = 0; idx < review.Score; idx++)
            {
                <i class="fa fa-star rating-color"></i>
            }
            @for (var idx = review.Score; idx < 5; idx++)
            {
                <i class="fa fa-star"></i>
            }
        </div>
    </div>
    <p class="text-start">
        @review.Text
    </p>
}

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Views/Shared/Components/Specification/Default.cshtml
@model ACME.Backend.Models.SpecificationModel[]

<div class="text-left">
@foreach (var spec in Model)
{
    <div class="row row-cols-lg-4">
        <div class="col">@spec.Key</div>
        <div class="col">@spec.Value</div>
    </div>
}
</div>

Exercises/Exercise 2/Starter/Frontend/ACME.Frontend.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACME Webshop</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="Productgroups">Productgroups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="AllProducts">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ACME - <a asp-controller="Product" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>